### PR TITLE
Fix up the licence and correctly attribute each party

### PR DESCRIPTION
**Pull request by MitchellCash**
The perils of find and replace mean we replace text we shouldn't, but the beauty of Git means I can easily fix it 👍

### CODE REVIEW

**Comment by adammatlack** [comment]
Should we properly credit these in the qt about as well?

**Comment by MitchellCash** [comment]
@adammatlack correct. Leave this open and I will fix it up. There is probably other licensing around that needs fixing, but I'll just get the most critical for now.

**Comment by MitchellCash** [comment]
@adammatlack fixed for review

**Comment by adammatlack** [comment]
this looks right to me.

**Review by adammatlack — APPROVED** [review]
nice, credited correctly.

**Pull request merged**
